In [20]:
import pandas as pd
import os
import pickle

In [49]:
prediction_df = []
prediction_dir = "/n/holylfs06/LABS/mzitnik_lab/Lab/afang/protein_universe/foldseek_cluster/processed_A0A6B2YTG2/"
for fname in os.listdir(prediction_dir):
    if fname.endswith(".csv") and 'prediction' in fname:
        df = pd.read_csv(os.path.join(prediction_dir, fname))
        df['ligand'] = fname.split('_')[0]
        prediction_df.append(df)
prediction_df = pd.concat(prediction_df)

In [50]:
prediction_df.groupby(['id', 'ligand']).agg({'predicted': 'mean', 'predicted': 'std'})

                                  predicted
id                        ligand
A0A0K3BHV0                CU       0.004821
                          HEM      0.005072
A0A2T0LHX9                CU       0.004120
                          HEM      0.016092
A0A2V8JCM5                CU       0.004925
                          HEM      0.306905
AF-A0A6B2YTG2-F1-model_v4 HEM      0.555501

In [37]:
# A0A2V8JCM5
# A0A6B2YTG2
# A0A0K3BHV0
print(prediction_df[prediction_df['id'] == 'A0A0K3BHV0']['predicted'].mean())
prediction_df[prediction_df['id'] == 'A0A0K3BHV0']

0.3336500576666666

   predicted  label          id ligand
0   0.029298    NaN  A0A0K3BHV0    HEM
0   0.001965    NaN  A0A0K3BHV0    HEM
0   0.969687    NaN  A0A0K3BHV0    HEM

In [41]:
print(prediction_df[prediction_df['id'] == 'A0A2T0LHX9']['predicted'].mean())
prediction_df[prediction_df['id'] == 'A0A2T0LHX9']

nan

Empty DataFrame
Columns: [predicted, label, id, ligand]
Index: []

In [38]:
print(prediction_df[prediction_df['id'] == 'A0A2V8JCM5']['predicted'].mean())
prediction_df[prediction_df['id'] == 'A0A2V8JCM5']

0.0022703861

     predicted  label          id ligand
109   0.001386    NaN  A0A2V8JCM5    HEM
109   0.000357    NaN  A0A2V8JCM5    HEM
109   0.005069    NaN  A0A2V8JCM5    HEM

In [39]:
with open(os.path.join(prediction_dir, 'pesto_80_ligand.pkl'), 'rb') as f:
    data = pickle.load(f)
data_ids = [x['id'] for x in data]

In [42]:
'A0A2T0LHX9' in data_ids

False